name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  # TODO: Change variable to your image's name.
  GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: cd cmd/crawler-cli; go test -v ./...
    
    - name: Setup yarn
      uses: actions/setup-node@v2
      
    - name: Build web
      run: cd web; yarn && yarn build
